version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: project_management_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-project_management_db}
      POSTGRES_USER: ${DATABASE_USERNAME:-user_project}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password_project}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-user_project} -d ${DATABASE_NAME:-project_management_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local 