import { BadRequestException } from '@nestjs/common';
import {
  SyncEntityType,
  SyncOperation,
  type SyncPushChangeDto,
} from './dto/sync-push.dto';
import { SyncChangeParser } from './sync-change.parser';

const tenantId = '11111111-1111-4111-8111-111111111111';

describe('SyncChangeParser', () => {
  const parser = new SyncChangeParser();

  it('accepts a Work UUID generated by the client', () => {
    expect(parser.parse(tenantId, workChange()).workId).toBe(
      '44444444-4444-4444-8444-444444444444'
    );
  });

  it('rejects a payload from another tenant', () => {
    const change = workChange();
    change.payload.tenantId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

    expect(() => parser.parse(tenantId, change)).toThrow(BadRequestException);
  });

  it('preserves the offline work snapshot in the parsed Push payload', () => {
    const change = workChange();
    change.payload.formSnapshot = {
      workId: change.entityId,
      tenantId,
      formTemplateId: change.payload.formTemplateId,
      formTemplateVersion: 1,
      name: 'Inspección offline',
      sections: [],
    };

    expect(parser.parse(tenantId, change).parsedPayload).toMatchObject({
      formSnapshot: expect.objectContaining({
        workId: change.entityId,
        tenantId,
      }),
    });
  });

  it('validates an optional offline measurement day', () => {
    const change: SyncPushChangeDto = {
      ...workChange(),
      entityType: SyncEntityType.RESPONSE,
      entityId: '99999999-9999-4999-8999-999999999999',
      payload: {
        id: '99999999-9999-4999-8999-999999999999',
        tenantId,
        workId: '44444444-4444-4444-8444-444444444444',
        formItemId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        conceptId: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
        valueNumber: 85,
        measuredAt: '2026-09-15',
        measuredAtTime: '14:35',
      },
    };
    expect(parser.parse(tenantId, change).parsedPayload).toMatchObject({
      measuredAt: '2026-09-15',
      measuredAtTime: '14:35',
    });
    change.payload.measuredAt = 'invalid';
    expect(() => parser.parse(tenantId, change)).toThrow(BadRequestException);
    change.payload.measuredAt = '2026-09-15';
    change.payload.measuredAtTime = '25:91';
    expect(() => parser.parse(tenantId, change)).toThrow(BadRequestException);
  });
});

function workChange(): SyncPushChangeDto {
  const id = '44444444-4444-4444-8444-444444444444';
  return {
    outboxId: '33333333-3333-4333-8333-333333333333',
    entityType: SyncEntityType.WORK,
    entityId: id,
    operation: SyncOperation.CREATE,
    clientTimestamp: '2026-09-15T12:00:00.000Z',
    payload: {
      id,
      tenantId,
      siteId: '55555555-5555-4555-8555-555555555555',
      assetId: '66666666-6666-4666-8666-666666666666',
      workTypeId: '77777777-7777-4777-8777-777777777777',
      formTemplateId: '88888888-8888-4888-8888-888888888888',
      formTemplateVersion: 1,
      title: 'Inspección offline',
      executionDate: '2026-09-15',
      responsible: 'Inspector',
      status: 'DRAFT',
    },
  };
}
