import { BadRequestException } from '@nestjs/common';
import {
  SyncEntityType,
  SyncOperation,
  type SyncPushChangeDto,
} from './dto/sync-push.dto';
import { SyncChangeParser } from './sync-change.parser';

const tenantId = '11111111-1111-4111-8111-111111111111';

describe('SyncChangeParser', () => {
  const parser = new SyncChangeParser();

  it('accepts a Work UUID generated by the client', () => {
    expect(parser.parse(tenantId, workChange()).workId).toBe(
      '44444444-4444-4444-8444-444444444444'
    );
  });

  it('rejects a payload from another tenant', () => {
    const change = workChange();
    change.payload.tenantId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

    expect(() => parser.parse(tenantId, change)).toThrow(BadRequestException);
  });
});

function workChange(): SyncPushChangeDto {
  const id = '44444444-4444-4444-8444-444444444444';
  return {
    outboxId: '33333333-3333-4333-8333-333333333333',
    entityType: SyncEntityType.WORK,
    entityId: id,
    operation: SyncOperation.CREATE,
    clientTimestamp: '2026-09-15T12:00:00.000Z',
    payload: {
      id,
      tenantId,
      siteId: '55555555-5555-4555-8555-555555555555',
      assetId: '66666666-6666-4666-8666-666666666666',
      workTypeId: '77777777-7777-4777-8777-777777777777',
      formTemplateId: '88888888-8888-4888-8888-888888888888',
      formTemplateVersion: 1,
      title: 'Inspección offline',
      executionDate: '2026-09-15',
      responsible: 'Inspector',
      status: 'DRAFT',
    },
  };
}
