import type { Asset, Site, Tenant } from './models';

export const mockTenants: Tenant[] = [
  { id: 'tenant-minera-andina', name: 'Empresa Minera Andina' },
  { id: 'tenant-energia-pacifico', name: 'Energía del Pacífico' },
];

export const mockSites: Site[] = [
  {
    id: 'site-andina-norte',
    tenantId: 'tenant-minera-andina',
    code: 'MAN',
    name: 'Mina Andina Norte',
    type: 'MINE',
    active: true,
  },
  {
    id: 'site-andina-sur',
    tenantId: 'tenant-minera-andina',
    code: 'MAS',
    name: 'Mina Andina Sur',
    type: 'MINE',
    active: true,
  },
  {
    id: 'site-pacifico-planta',
    tenantId: 'tenant-energia-pacifico',
    code: 'PEP',
    name: 'Planta Eléctrica Pacífico',
    type: 'PLANT',
    active: true,
  },
  {
    id: 'site-pacifico-cordillera',
    tenantId: 'tenant-energia-pacifico',
    code: 'PEC',
    name: 'Faena Cordillera',
    type: 'SITE',
    active: true,
  },
];

export const mockAssets: Asset[] = [
  // Empresa Minera Andina · Mina Andina Norte
  {
    id: 'asset-a-norte-se-001',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'SE-001',
    name: 'Subestación Chancado',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
    description: 'Subestación principal del área de chancado primario.',
  },
  {
    id: 'asset-a-norte-t1',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'TR-001',
    name: 'Transformador T1',
    type: 'POWER_TRANSFORMER',
    parentId: 'asset-a-norte-se-001',
    status: 'ACTIVE',
    description: 'Transformador de poder 110/23 kV.',
  },
  {
    id: 'asset-a-norte-t1-rad',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'RAD-T1',
    name: 'Banco de radiadores',
    type: 'RADIATOR_BANK',
    parentId: 'asset-a-norte-t1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-t1-bush',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'BUSH-T1',
    name: 'Bushings de alta tensión',
    type: 'BUSHINGS',
    parentId: 'asset-a-norte-t1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-t1-oltc',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'OLTC-T1',
    name: 'Cambiador bajo carga',
    type: 'TAP_CHANGER',
    parentId: 'asset-a-norte-t1',
    status: 'OUT_OF_SERVICE',
  },
  {
    id: 'asset-a-norte-control-1',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'SC-001',
    name: 'Sala de control',
    type: 'CONTROL_ROOM',
    parentId: 'asset-a-norte-se-001',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-prot-1',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'PR-001',
    name: 'Tablero de protecciones',
    type: 'PROTECTION_PANEL',
    parentId: 'asset-a-norte-control-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-com-1',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'COM-001',
    name: 'Gabinete de comunicaciones',
    type: 'COMMUNICATIONS',
    parentId: 'asset-a-norte-control-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-se-002',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'SE-002',
    name: 'Subestación Correas',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
    description: 'Alimenta correas transportadoras y servicios auxiliares.',
  },
  {
    id: 'asset-a-norte-int-1',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: '52B-01',
    name: 'Interruptor principal',
    type: 'CIRCUIT_BREAKER',
    parentId: 'asset-a-norte-se-002',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-int-drive',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'MEC-52B-01',
    name: 'Mecanismo de accionamiento',
    type: 'DRIVE_MECHANISM',
    parentId: 'asset-a-norte-int-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-ct-1',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'TC-001',
    name: 'Transformador de corriente',
    type: 'CURRENT_TRANSFORMER',
    parentId: 'asset-a-norte-se-002',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-norte-bat-1',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-norte',
    code: 'BAT-001',
    name: 'Banco de baterías',
    type: 'BATTERY_BANK',
    parentId: 'asset-a-norte-se-002',
    status: 'INACTIVE',
  },

  // Empresa Minera Andina · Mina Andina Sur
  {
    id: 'asset-a-sur-se-003',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'SE-003',
    name: 'Subestación Planta Sur',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-sur-t2',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'TR-002',
    name: 'Transformador T2',
    type: 'POWER_TRANSFORMER',
    parentId: 'asset-a-sur-se-003',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-sur-t2-rad',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'RAD-T2',
    name: 'Radiadores T2',
    type: 'RADIATOR_BANK',
    parentId: 'asset-a-sur-t2',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-sur-t2-bush',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'BUSH-T2',
    name: 'Bushings T2',
    type: 'BUSHINGS',
    parentId: 'asset-a-sur-t2',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-sur-se-004',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'SE-004',
    name: 'Subestación Servicios Mina',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-sur-control-2',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'SC-004',
    name: 'Sala eléctrica',
    type: 'CONTROL_ROOM',
    parentId: 'asset-a-sur-se-004',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-sur-dc-2',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'TCC-004',
    name: 'Tablero de corriente continua',
    type: 'DC_PANEL',
    parentId: 'asset-a-sur-control-2',
    status: 'ACTIVE',
  },
  {
    id: 'asset-a-sur-charger-2',
    tenantId: 'tenant-minera-andina',
    siteId: 'site-andina-sur',
    code: 'CRG-004',
    name: 'Cargador de baterías',
    type: 'BATTERY_CHARGER',
    parentId: 'asset-a-sur-dc-2',
    status: 'ACTIVE',
  },

  // Energía del Pacífico · Planta Eléctrica Pacífico
  {
    id: 'asset-p-planta-se-101',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'SE-101',
    name: 'Subestación Generación',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-planta-gsu-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'GSU-01',
    name: 'Transformador elevador GSU-1',
    type: 'POWER_TRANSFORMER',
    parentId: 'asset-p-planta-se-101',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-planta-cool-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'ENF-GSU-01',
    name: 'Sistema de enfriamiento',
    type: 'COOLING_SYSTEM',
    parentId: 'asset-p-planta-gsu-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-planta-fans-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'VEN-GSU-01',
    name: 'Grupo de ventiladores',
    type: 'FAN_GROUP',
    parentId: 'asset-p-planta-cool-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-planta-se-102',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'SE-102',
    name: 'Subestación Servicios Auxiliares',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-planta-tss-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'TSA-01',
    name: 'Transformador de servicios',
    type: 'AUXILIARY_TRANSFORMER',
    parentId: 'asset-p-planta-se-102',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-planta-panel-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'TSA-BT-01',
    name: 'Tablero de baja tensión',
    type: 'LOW_VOLTAGE_PANEL',
    parentId: 'asset-p-planta-tss-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-planta-ups-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-planta',
    code: 'UPS-01',
    name: 'UPS de control',
    type: 'UPS',
    parentId: 'asset-p-planta-se-102',
    status: 'OUT_OF_SERVICE',
  },

  // Energía del Pacífico · Faena Cordillera
  {
    id: 'asset-p-cord-se-201',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'SE-201',
    name: 'Subestación Campamento',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-cord-tr-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'TR-201',
    name: 'Transformador de distribución',
    type: 'DISTRIBUTION_TRANSFORMER',
    parentId: 'asset-p-cord-se-201',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-cord-cell-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'CEL-201-A',
    name: 'Celda de media tensión A',
    type: 'MEDIUM_VOLTAGE_CELL',
    parentId: 'asset-p-cord-se-201',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-cord-relay-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'REL-201-A',
    name: 'Relé de protección',
    type: 'PROTECTION_RELAY',
    parentId: 'asset-p-cord-cell-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-cord-se-202',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'SE-202',
    name: 'Subestación Bombeo',
    type: 'SUBSTATION',
    parentId: null,
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-cord-feeder-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'ALI-202-01',
    name: 'Alimentador Bombas 1',
    type: 'FEEDER',
    parentId: 'asset-p-cord-se-202',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-cord-breaker-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: '52B-202-01',
    name: 'Interruptor Alimentador 1',
    type: 'CIRCUIT_BREAKER',
    parentId: 'asset-p-cord-feeder-1',
    status: 'ACTIVE',
  },
  {
    id: 'asset-p-cord-feeder-2',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'ALI-202-02',
    name: 'Alimentador Bombas 2',
    type: 'FEEDER',
    parentId: 'asset-p-cord-se-202',
    status: 'INACTIVE',
  },
  {
    id: 'asset-p-cord-control-1',
    tenantId: 'tenant-energia-pacifico',
    siteId: 'site-pacifico-cordillera',
    code: 'SC-202',
    name: 'Sala de control bombeo',
    type: 'CONTROL_ROOM',
    parentId: 'asset-p-cord-se-202',
    status: 'ACTIVE',
  },
];
