'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, CheckCircle2, Eye, FileBadge, HeartPulse, Info, Loader2, MapPinned, PlaneTakeoff, Plus, ShieldCheck, Trash2, UserRound, UsersRound, X } from 'lucide-react';
import { createDocument, createResource, deleteDocument, deleteResource, DocumentType, getDocuments, getProfile, getResources, TravelDocument, TravelerProfile, TravelerResource, updateDocument, updateProfile, uploadDocumentFile } from '@/services/travelerProfileService';
import { DocumentViewer } from './DocumentViewer';

const TYPES:{value:DocumentType;label:string}[]=[{value:'passport',label:'Pasaporte'},{value:'identity',label:'Documento de identidad'},{value:'visa',label:'Visa o permiso'},{value:'driver_license',label:'Licencia de conducir'},{value:'travel_insurance',label:'Seguro de viaje'},{value:'vaccination',label:'Certificado de vacunación'},{value:'prescription',label:'Receta médica'},{value:'other',label:'Otro documento'}];
const status={valid:['Vigente','bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300'],expiring:['Vence pronto','bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300'],expired:['Vencido','bg-red-50 text-red-700 dark:bg-red-950/50 dark:text-red-300'],no_date:['Sin vencimiento','bg-muted text-muted-foreground']} as const;

export function TravelerProfileView(){
 const [profile,setProfile]=useState<TravelerProfile|null>(null),[documents,setDocuments]=useState<TravelDocument[]>([]),[resources,setResources]=useState<TravelerResource[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState<'document'|'contact'|'address'|'insurance'|null>(null);
 const load=async()=>{try{const [p,d,r]=await Promise.all([getProfile(),getDocuments(),getResources()]);setProfile(p);setDocuments(d);setResources(r);setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el perfil')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 if(loading)return <div className="flex min-h-screen items-center justify-center gap-2 text-muted-foreground"><Loader2 className="size-5 animate-spin"/>Cargando tu bóveda segura…</div>;
 if(!profile)return <div className="mx-auto max-w-xl p-8 text-center text-red-700 dark:text-red-300">{error}</div>;
 const contacts=resources.filter(r=>r.kind==='emergency_contact'),addresses=resources.filter(r=>r.kind==='important_address'),insurances=resources.filter(r=>r.kind==='insurance');
 return <div className="mx-auto max-w-7xl px-4 py-5 sm:px-7 sm:py-8">
  <header className="overflow-hidden rounded-[28px] bg-gradient-to-br from-sky-700 via-blue-700 to-indigo-800 p-6 text-white shadow-xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><Link href="/" className="mb-5 inline-flex items-center gap-2 text-sm text-white/75 hover:text-white"><ArrowLeft className="size-4"/>Volver al viaje activo</Link><p className="text-sm font-semibold text-cyan-100">Mi información permanente</p><h1 className="mt-1 text-3xl font-bold">Mi perfil de viajero</h1><p className="mt-2 max-w-2xl text-sm text-blue-100">Datos privados y recursos reutilizables en todos tus viajes. Aquí no se guardan reservas ni alojamientos de un viaje específico.</p></div><ShieldCheck className="hidden size-12 text-cyan-200 sm:block"/></div><div className="mt-7 flex items-center gap-4"><div className="h-2 flex-1 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-cyan-300" style={{width:`${profile.summary.completion}%`}}/></div><span className="text-sm font-bold">{profile.summary.completion}% completo</span></div></header>
  <section className="mt-5 grid gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950 dark:border-blue-800 dark:bg-blue-950/40 dark:text-blue-100 sm:grid-cols-[auto_1fr_auto] sm:items-center"><Info className="size-5 text-blue-600 dark:text-blue-400"/><p><strong>Este perfil es solo tuyo.</strong> Para elegir qué documentos llevarás en el viaje activo, utiliza la sección <strong>Preparación</strong> del viaje.</p><Link href="/" className="inline-flex items-center gap-2 font-semibold text-blue-700 hover:text-blue-900 dark:text-blue-300 dark:hover:text-blue-100"><PlaneTakeoff className="size-4"/>Ir a Preparación</Link></section>
  {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/40 dark:text-red-300">{error}</p>}
  <section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Vigentes',profile.summary.valid,'text-emerald-700 dark:text-emerald-400'],['Próximos a vencer',profile.summary.expiring,'text-amber-700 dark:text-amber-400'],['Vencidos',profile.summary.expired,'text-red-700 dark:text-red-400'],['Documentos',documents.length,'text-blue-700 dark:text-blue-400']].map(([l,n,c])=><div key={String(l)} className="rounded-2xl border bg-card p-4 shadow-sm"><p className={`text-2xl font-bold ${c}`}>{n}</p><p className="text-xs text-muted-foreground">{l}</p></div>)}</section>
  {profile.summary.alerts.length>0&&<section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-800 dark:bg-amber-950/40"><h2 className="flex items-center gap-2 font-semibold text-amber-900 dark:text-amber-200"><AlertTriangle className="size-4"/>Atención</h2>{profile.summary.alerts.map((a,i)=><p key={i} className="mt-1 text-sm text-amber-800 dark:text-amber-300">{a.message}</p>)}</section>}
  <PersonalCard profile={profile} saved={load}/>
  <Section title="Bóveda de documentos" icon={<FileBadge/>} action={()=>setModal('document')} empty="Aún no has agregado documentos. Guarda una copia segura para tenerla disponible durante tu viaje.">{documents.map(d=><DocumentCard key={d.id} document={d} reload={load}/>)}</Section>
  <div className="grid gap-5 lg:grid-cols-3"><Section title="Contactos de emergencia" icon={<UsersRound/>} action={()=>setModal('contact')} empty="No tienes contactos de emergencia registrados.">{contacts.map(r=><ResourceCard key={r.id} r={r} reload={load}/>)}</Section><Section title="Seguros reutilizables" icon={<ShieldCheck/>} action={()=>setModal('insurance')} empty="No tienes seguros registrados.">{insurances.map(r=><ResourceCard key={r.id} r={r} reload={load}/>)}</Section><Section title="Direcciones frecuentes" icon={<MapPinned/>} action={()=>setModal('address')} empty="Guarda domicilios, consulados u otras direcciones que reutilices. Los hoteles pertenecen a cada viaje.">{addresses.map(r=><ResourceCard key={r.id} r={r} reload={load}/>)}</Section></div>
  <section className="mt-5 rounded-2xl border border-purple-200 bg-purple-50 p-5 dark:border-purple-800 dark:bg-purple-950/40"><h2 className="flex items-center gap-2 font-semibold text-purple-950 dark:text-purple-200"><HeartPulse className="size-5"/>Información médica opcional</h2><p className="mt-1 text-sm text-purple-800 dark:text-purple-300">Es privada y no se comparte con participantes por defecto. Puedes agregarla en Información personal cuando la necesites.</p></section>
  {modal&&<CreateModal kind={modal} close={()=>setModal(null)} done={()=>{setModal(null);load()}}/>}
 </div>;
}
function Section({title,icon,action,empty,children}:{title:string;icon:React.ReactNode;action:()=>void;empty:string;children:React.ReactNode}){const has=Array.isArray(children)?children.length>0:!!children;return <section className="mt-5 rounded-3xl border bg-card/75 p-5 shadow-sm backdrop-blur"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-bold">{icon}{title}</h2><button onClick={action} className="inline-flex items-center gap-1 rounded-xl bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground"><Plus className="size-4"/>Agregar</button></div>{has?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{children}</div>:<p className="rounded-2xl border border-dashed p-6 text-center text-sm text-muted-foreground">{empty}</p>}</section>}
function ResourceCard({r,reload}:{r:TravelerResource;reload:()=>void}){return <article className="rounded-2xl border bg-background p-4"><p className="font-semibold">{r.name}</p><p className="mt-1 text-xs text-muted-foreground">{String(r.data.phone||r.data.company||r.data.address||'Información guardada')}</p><button onClick={async()=>{if(confirm('¿Eliminar este registro?')){await deleteResource(r.id);reload()}}} className="mt-3 text-xs text-red-600 dark:text-red-400">Eliminar</button></article>}
function DocumentCard({document:d,reload}:{document:TravelDocument;reload:()=>void}){const [busy,setBusy]=useState(false),[preview,setPreview]=useState<{id:string;label:string}|null>(null);const upload=async(file?:File)=>{if(!file)return;setBusy(true);try{const stored=await uploadDocumentFile(d.id,file);await updateDocument(d.id,{fileIds:[...(d.fileIds||[]),stored.id]});reload()}finally{setBusy(false)}};return <><article className="rounded-2xl border bg-background p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{d.displayName}</p><p className="mt-1 text-xs text-muted-foreground">{TYPES.find(t=>t.value===d.type)?.label} · {d.maskedNumber||'Número no registrado'}</p></div><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${status[d.status][1]}`}>{status[d.status][0]}</span></div><p className="mt-3 text-xs text-muted-foreground">{d.expiresAt?`Vence: ${new Date(`${d.expiresAt}T12:00:00`).toLocaleDateString('es-CL')}`:'Sin fecha de vencimiento'}</p><div className="mt-3 flex flex-wrap gap-3 text-xs">{d.fileIds?.map((id,i)=><button key={id} type="button" onClick={()=>setPreview({id,label:`${d.displayName} · archivo ${i+1}`})} className="inline-flex items-center gap-1 font-semibold text-blue-700 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-200"><Eye className="size-3.5"/>Ver archivo {i+1}</button>)}<label className="cursor-pointer font-semibold text-blue-700 dark:text-blue-400">{busy?'Subiendo…':'Adjuntar PDF o imagen'}<input className="hidden" type="file" accept="application/pdf,image/jpeg,image/png,image/heic,image/heif" capture="environment" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></label><button onClick={async()=>{if(confirm('¿Eliminar este documento y sus metadatos?')){await deleteDocument(d.id);reload()}}} className="inline-flex items-center gap-1 text-red-600 dark:text-red-400"><Trash2 className="size-3"/>Eliminar</button></div></article>{preview&&<DocumentViewer fileId={preview.id} title={preview.label} onClose={()=>setPreview(null)}/>}</>}
function PersonalCard({profile,saved}:{profile:TravelerProfile;saved:()=>void}){const [editing,setEditing]=useState(false);const [name,setName]=useState(profile.personal.fullName||''),[phone,setPhone]=useState(profile.personal.phone||''),[nationality,setNationality]=useState(profile.personal.nationality||'');const submit=async(e:FormEvent)=>{e.preventDefault();await updateProfile({personal:{fullName:name,phone,nationality}} as Partial<TravelerProfile>);setEditing(false);saved()};return <section className="mt-5 rounded-3xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-bold"><UserRound/>Información personal</h2><button onClick={()=>setEditing(!editing)} className="text-sm font-semibold text-blue-700 dark:text-blue-400">{editing?'Cancelar':'Editar'}</button></div>{editing?<form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-3"><Input label="Nombre completo" value={name} set={setName}/><Input label="Teléfono" value={phone} set={setPhone}/><Input label="Nacionalidad" value={nationality} set={setNationality}/><button className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground sm:col-span-3">Guardar cambios</button></form>:<div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p><span className="text-muted-foreground">Nombre:</span> {name||'Pendiente'}</p><p><span className="text-muted-foreground">Teléfono:</span> {phone||'Pendiente'}</p><p><span className="text-muted-foreground">Nacionalidad:</span> {nationality||'Pendiente'}</p></div>}</section>}
function Input({label,value,set,type='text',required=false}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean}){return <label className="text-xs font-medium text-muted-foreground">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} required={required} className="mt-1 w-full rounded-xl border bg-background px-3 py-2 text-sm text-foreground outline-none focus:ring-2 focus:ring-ring"/></label>}
function CreateModal({kind,close,done}:{kind:'document'|'contact'|'address'|'insurance';close:()=>void;done:()=>void}){const [name,setName]=useState(''),[secondary,setSecondary]=useState(''),[type,setType]=useState<DocumentType>('passport'),[number,setNumber]=useState(''),[expiry,setExpiry]=useState(''),[saving,setSaving]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{if(kind==='document')await createDocument({displayName:name,type,documentNumber:number,expiresAt:expiry||undefined});else await createResource({kind:kind==='contact'?'emergency_contact':kind==='address'?'important_address':'insurance',name,data:{[kind==='contact'?'phone':kind==='address'?'address':'company']:secondary}});done()}finally{setSaving(false)}};return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/65 p-0 sm:items-center sm:p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-t-3xl border bg-card p-6 text-card-foreground shadow-2xl sm:rounded-3xl"><div className="flex justify-between"><h2 className="text-xl font-bold">Agregar {kind==='document'?'documento':kind==='contact'?'contacto':kind==='address'?'dirección frecuente':'seguro'}</h2><button type="button" onClick={close}><X/></button></div>{kind==='address'&&<p className="mt-2 text-sm text-muted-foreground">Guarda aquí domicilios o lugares reutilizables. Agrega hoteles y alojamientos dentro del viaje correspondiente.</p>}<div className="mt-5 grid gap-4">{kind==='document'&&<label className="text-xs font-medium text-muted-foreground">Tipo<select value={type} onChange={e=>setType(e.target.value as DocumentType)} className="mt-1 w-full rounded-xl border bg-background p-2 text-sm text-foreground">{TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label>}<Input label="Nombre visible" value={name} set={setName} required/>{kind==='document'?<><Input label="Número (se mostrará enmascarado)" value={number} set={setNumber}/><Input label="Fecha de vencimiento" value={expiry} set={setExpiry} type="date"/></>:<Input label={kind==='contact'?'Teléfono':kind==='address'?'Dirección reutilizable':'Compañía aseguradora'} value={secondary} set={setSecondary}/>}</div><button disabled={saving} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3 font-semibold text-primary-foreground disabled:opacity-60">{saving?<Loader2 className="size-4 animate-spin"/>:<CheckCircle2 className="size-4"/>}Guardar</button></form></div>}
