'use client';
import { useEffect, useMemo, useState } from 'react';
import { X, ReceiptText, Loader2 } from 'lucide-react';
import { CURRENCIES, EXPENSE_CATEGORIES, Expense, ExpenseCategory, ExpenseInput, SplitMethod } from '@/lib/finance';
import type { Activity } from '@/lib/types';

interface Person { id:string; label:string }
interface Props { open:boolean;expense?:Expense|null;baseCurrency:string;people:Person[];activities:Activity[];currentUserId:string;onClose:()=>void;onSave:(input:ExpenseInput)=>Promise<void> }
const nowLocal=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)};

export function ExpenseFormModal({open,expense,baseCurrency,people,activities,currentUserId,onClose,onSave}:Props){
  const [title,setTitle]=useState(''); const [amount,setAmount]=useState(''); const [currency,setCurrency]=useState(baseCurrency); const [rate,setRate]=useState('1');
  const [category,setCategory]=useState<ExpenseCategory>('food'); const [date,setDate]=useState(nowLocal()); const [payer,setPayer]=useState(currentUserId);
  const [type,setType]=useState<'individual'|'shared'>('individual'); const [method,setMethod]=useState<SplitMethod>('equal'); const [participants,setParticipants]=useState<string[]>([currentUserId]);
  const [values,setValues]=useState<Record<string,string>>({}); const [status,setStatus]=useState<ExpenseInput['status']>('paid'); const [city,setCity]=useState(''); const [notes,setNotes]=useState(''); const [activityId,setActivityId]=useState(''); const [receiptUrl,setReceiptUrl]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(!open)return; if(expense){setTitle(expense.title);setAmount(expense.amount);setCurrency(expense.originalCurrency);setRate(expense.exchangeRate);setCategory(expense.category);setDate(expense.incurredAt.slice(0,16));setPayer(expense.payerUserId);setType(expense.expenseType);setMethod(expense.splitMethod);setParticipants(expense.splits.map(s=>s.participantUserId));let splitValues=Object.fromEntries(expense.splits.map(s=>[s.participantUserId,expense.splitMethod==='percentage'?s.percentage??'':expense.splitMethod==='shares'?s.shares??'':s.amount]));if(expense.splitMethod==='custom_amount'&&expense.originalCurrency!==expense.baseCurrency){const digits=expense.originalCurrency==='CLP'?0:2;const rows=expense.splits.map(s=>Number(s.amount)/Number(expense.exchangeRate));const previous=rows.slice(0,-1).map(value=>Number(value.toFixed(digits)));rows[rows.length-1]=Number(expense.amount)-previous.reduce((a,b)=>a+b,0);splitValues=Object.fromEntries(expense.splits.map((s,i)=>[s.participantUserId,rows[i].toFixed(digits)]));}setValues(splitValues);setStatus(expense.status);setCity(expense.city??'');setNotes(expense.notes??'');setActivityId(expense.activityId??'');setReceiptUrl(expense.receiptUrl??'');}else{setTitle('');setAmount('');setCurrency(baseCurrency);setRate('1');setCategory('food');setDate(nowLocal());setPayer(currentUserId);setType('individual');setMethod('equal');setParticipants([currentUserId]);setValues({});setStatus('paid');setCity('');setNotes('');setActivityId('');setReceiptUrl('');}setError('');},[open,expense,baseCurrency,currentUserId]);
  const preview=useMemo(()=>{const n=Number(amount)||0;if(!participants.length)return[];if(method==='equal'||method==='gift')return participants.map((id,i)=>({id,value:(n/participants.length).toFixed(currency==='CLP'?0:2),residual:i===participants.length-1}));if(method==='percentage')return participants.map(id=>({id,value:(n*(Number(values[id])||0)/100).toFixed(currency==='CLP'?0:2)}));return participants.map(id=>({id,value:values[id]||'0'}));},[amount,currency,method,participants,values]);
  if(!open)return null;
  function toggle(id:string){setParticipants(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);}
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!participants.length){setError('Selecciona al menos un participante.');return;}if(type==='individual'&&participants.length!==1){setError('Un gasto individual debe tener una persona.');return;}const splits=participants.map(id=>({participantUserId:id,...(method==='custom_amount'?{amount:values[id]||'0'}:method==='percentage'?{percentage:values[id]||'0'}:method==='shares'?{shares:values[id]||'0'}:{})}));try{setSaving(true);await onSave({title,amount,currency,exchangeRate:currency===baseCurrency?'1':rate,exchangeRateDate:new Date().toISOString().slice(0,10),exchangeRateSource:currency===baseCurrency?'identity':'manual',category,incurredAt:new Date(date).toISOString(),city:city||undefined,payerUserId:payer,expenseType:type,splitMethod:method,splits,activityId:activityId||undefined,status,notes:notes||undefined,receiptUrl:receiptUrl||undefined});onClose();}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar el gasto');}finally{setSaving(false);}}
  const input='h-10 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring/30';
  return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center sm:p-4" role="dialog" aria-modal="true"><button className="absolute inset-0 bg-black/45 backdrop-blur-sm" onClick={onClose} aria-label="Cerrar"/><div className="relative flex max-h-[94vh] w-full flex-col rounded-t-3xl border bg-card shadow-2xl sm:max-w-2xl sm:rounded-3xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">{expense?'Editar gasto':'Registrar gasto'}</h2><p className="text-xs text-muted-foreground">Los balances se recalculan automáticamente</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-muted"><X className="size-4"/></button></div><form onSubmit={submit} className="overflow-y-auto"><div className="space-y-5 p-5">
    <div><label className="mb-1 block text-xs font-semibold">Descripción</label><input required value={title} onChange={e=>setTitle(e.target.value)} className={input} placeholder="Ej: Cena en Roma"/></div>
    <div className="grid grid-cols-[1fr_110px] gap-3"><div><label className="mb-1 block text-xs font-semibold">Monto</label><input required min="0.01" step="0.01" type="number" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className={input}/></div><div><label className="mb-1 block text-xs font-semibold">Moneda</label><select value={currency} onChange={e=>{setCurrency(e.target.value);setRate(e.target.value===baseCurrency?'1':'')}} className={input}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></div></div>
    {currency!==baseCurrency&&<div className="rounded-2xl bg-amber-50 p-3"><label className="mb-1 block text-xs font-semibold text-amber-900">1 {currency} equivale a cuántos {baseCurrency}</label><input required value={rate} onChange={e=>setRate(e.target.value)} className={input}/><p className="mt-1 text-[11px] text-amber-700">Conversión manual aproximada; se conserva el monto original.</p></div>}
    <div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-1 block text-xs font-semibold">Categoría</label><select value={category} onChange={e=>setCategory(e.target.value as ExpenseCategory)} className={input}>{Object.entries(EXPENSE_CATEGORIES).map(([k,v])=><option key={k} value={k}>{v.icon} {v.label}</option>)}</select></div><div><label className="mb-1 block text-xs font-semibold">Fecha y hora</label><input required type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className={input}/></div></div>
    <div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-1 block text-xs font-semibold">Pagó</label><select value={payer} onChange={e=>setPayer(e.target.value)} className={input}>{people.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></div><div><label className="mb-1 block text-xs font-semibold">Estado</label><select value={status} onChange={e=>setStatus(e.target.value as ExpenseInput['status'])} className={input}><option value="paid">Pagado</option><option value="partial">Pago parcial</option><option value="pending">Pendiente</option><option value="estimated">Estimado</option><option value="cancelled">Cancelado</option></select></div></div>
    <div><label className="mb-2 block text-xs font-semibold">Tipo de gasto</label><div className="grid grid-cols-2 gap-2">{(['individual','shared'] as const).map(v=><button type="button" key={v} onClick={()=>{setType(v);if(v==='individual'){setParticipants([currentUserId]);setMethod('equal')}}} className={`rounded-xl border px-3 py-2 text-sm font-semibold ${type===v?'border-primary bg-primary/5 text-primary':'hover:bg-muted'}`}>{v==='individual'?'Individual':'Compartido'}</button>)}</div></div>
    <div><label className="mb-2 block text-xs font-semibold">Participantes</label><div className="flex flex-wrap gap-2">{people.map(p=><button type="button" disabled={type==='individual'} key={p.id} onClick={()=>toggle(p.id)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold disabled:opacity-70 ${participants.includes(p.id)?'border-primary bg-primary text-primary-foreground':'hover:bg-muted'}`}>{p.label}</button>)}</div></div>
    {type==='shared'&&<div><label className="mb-2 block text-xs font-semibold">División</label><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{([['equal','Igual'],['custom_amount','Montos'],['percentage','%'],['shares','Partes'],['gift','Invitación']] as [SplitMethod,string][]).map(([v,l])=><button type="button" key={v} onClick={()=>setMethod(v)} className={`rounded-xl border px-2 py-2 text-xs font-semibold ${method===v?'border-primary bg-primary/5 text-primary':'hover:bg-muted'}`}>{l}</button>)}</div></div>}
    <div className="rounded-2xl border bg-muted/30 p-3"><p className="mb-2 text-xs font-bold">Resumen de división</p><div className="space-y-2">{preview.map(row=><div key={row.id} className="flex items-center justify-between gap-3 text-sm"><span>{people.find(p=>p.id===row.id)?.label??row.id.slice(0,8)}</span>{['custom_amount','percentage','shares'].includes(method)?<div className="flex items-center gap-2"><input value={values[row.id]??''} onChange={e=>setValues(v=>({...v,[row.id]:e.target.value}))} type="number" min="0" step="0.01" className="h-8 w-24 rounded-lg border bg-background px-2 text-right"/><span className="w-8 text-xs text-muted-foreground">{method==='percentage'?'%':method==='shares'?'pts':currency}</span></div>:<strong>{row.value} {currency}</strong>}</div>)}</div>{method==='gift'&&<p className="mt-2 text-[11px] text-muted-foreground">La invitación se registra en estadísticas, pero no genera deuda.</p>}</div>
    <div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-1 block text-xs font-semibold">Actividad vinculada</label><select value={activityId} onChange={e=>setActivityId(e.target.value)} className={input}><option value="">Ninguna</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></div><div><label className="mb-1 block text-xs font-semibold">Ciudad</label><input value={city} onChange={e=>setCity(e.target.value)} className={input}/></div></div>
    <div><label className="mb-1 block text-xs font-semibold">Comprobante (URL)</label><input type="url" value={receiptUrl} onChange={e=>setReceiptUrl(e.target.value)} className={input} placeholder="https://…"/></div><div><label className="mb-1 block text-xs font-semibold">Notas</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} className="min-h-20 w-full rounded-xl border bg-background p-3 text-sm"/></div>
    {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  </div><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-card p-4"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60">{saving?<Loader2 className="size-4 animate-spin"/>:<ReceiptText className="size-4"/>}{expense?'Guardar cambios':'Guardar gasto'}</button></div></form></div></div>;
}
