export const EXPENSE_CATEGORIES = {
  accommodation:{label:'Alojamiento',icon:'🏨',color:'bg-amber-100 text-amber-800'}, transport:{label:'Transporte',icon:'✈️',color:'bg-sky-100 text-sky-800'}, food:{label:'Comida',icon:'🍽️',color:'bg-orange-100 text-orange-800'}, activities:{label:'Actividades',icon:'🎟️',color:'bg-emerald-100 text-emerald-800'}, shopping:{label:'Compras',icon:'🛍️',color:'bg-pink-100 text-pink-800'}, health:{label:'Salud',icon:'⚕️',color:'bg-red-100 text-red-800'}, insurance:{label:'Seguros',icon:'🛡️',color:'bg-blue-100 text-blue-800'}, documentation:{label:'Documentación',icon:'📄',color:'bg-violet-100 text-violet-800'}, luggage:{label:'Equipaje',icon:'🧳',color:'bg-indigo-100 text-indigo-800'}, gifts:{label:'Regalos',icon:'🎁',color:'bg-fuchsia-100 text-fuchsia-800'}, fees:{label:'Comisiones',icon:'🏦',color:'bg-slate-100 text-slate-800'}, other:{label:'Otros',icon:'•••',color:'bg-gray-100 text-gray-800'},
} as const;
export type ExpenseCategory=keyof typeof EXPENSE_CATEGORIES;
export type ExpenseStatus='estimated'|'pending'|'partial'|'paid'|'cancelled';
export type SplitMethod='equal'|'custom_amount'|'percentage'|'shares'|'gift';
export interface ExpenseSplit { participantUserId:string; amount:string; percentage?:string; shares?:string; generatesDebt:boolean; }
export interface Expense { id:string;title:string;amount:string;currency?:string;originalCurrency:string;exchangeRate:string;convertedAmount:string;baseCurrency:string;category:ExpenseCategory;subcategory?:string;incurredAt:string;city?:string;createdByUserId:string;payerUserId:string;expenseType:'individual'|'shared';splitMethod:SplitMethod;activityId?:string;paymentMethod?:string;status:ExpenseStatus;notes?:string;receiptUrl?:string;splits:ExpenseSplit[];createdAt:string;updatedAt:string; }
export interface ExpenseInput { title:string;amount:string;currency:string;exchangeRate?:string;exchangeRateDate?:string;exchangeRateSource?:string;category:ExpenseCategory;subcategory?:string;incurredAt:string;city?:string;payerUserId:string;expenseType:'individual'|'shared';splitMethod:SplitMethod;splits:Array<{participantUserId:string;amount?:string;percentage?:string;shares?:string;generatesDebt?:boolean}>;activityId?:string;paymentMethod?:string;status:ExpenseStatus;notes?:string;receiptUrl?:string; }
export interface FinanceSummary { currency:string;totalSpent:string;totalPlanned:string;totalCommitted:string;totalPaid:string;totalPending:string;budget:string|null;remaining:string|null;consumedPercent:number|null;dailyAverage:string;recommendedDaily:string|null;projectedFinal:string;topCategory:ExpenseCategory|null;topPayerUserId:string|null;recent:Expense[];balances:BalanceSummary; }
export interface BalanceSummary { currency:string;participants:Array<{userId:string;paid:string;consumed:string;net:string}>;debts:Array<{fromUserId:string;toUserId:string;amount:string}>;settlements:Array<{id:string;fromUserId:string;toUserId:string;amount:string;currency:string;settledAt:string;status:'posted'|'void';note?:string}>; }
export interface Budget { amount:string|null;currency:string;categoryBudgets:Record<string,string>;personalBudgets:Record<string,string>;alertThresholds:number[]; }
export const CURRENCIES=['USD','EUR','CLP','GBP','CHF','CAD','AUD','JPY','BRL','ARS','PEN'] as const;
export function formatMoney(value:string|number,currency:string){ return new Intl.NumberFormat('es-CL',{style:'currency',currency,maximumFractionDigits:currency==='CLP'?0:2}).format(Number(value)); }
