import { Activity, TravelDay } from './types'

export const SAMPLE_ACTIVITIES: Activity[] = [
  // Day 1 - Madrid, España
  {
    id: 'a1',
    title: 'Check-in Hotel Gran Vía',
    type: 'accommodation',
    date: '2025-09-01',
    startTime: '14:00',
    countries: ['España'],
    city: 'Madrid',
    location: 'Gran Vía 25, Madrid',
    description: 'Check-in a las 14h. Reserva confirmada.',
    status: 'confirmed',
    priority: 'high',
    link: 'https://example.com/booking',
  },
  {
    id: 'a2',
    title: 'Visita al Museo del Prado',
    type: 'sightseeing',
    date: '2025-09-01',
    startTime: '10:00',
    endTime: '13:00',
    countries: ['España'],
    city: 'Madrid',
    location: 'Paseo del Prado, Madrid',
    description: 'Entradas reservadas para las 10h.',
    status: 'reserved',
    priority: 'high',
  },
  {
    id: 'a3',
    title: 'Almuerzo en Sobrino de Botín',
    type: 'food',
    date: '2025-09-01',
    startTime: '14:30',
    endTime: '16:00',
    countries: ['España'],
    city: 'Madrid',
    location: 'Calle Cuchilleros 17, Madrid',
    description: 'El restaurante más antiguo del mundo. Reservar mesa.',
    status: 'pending',
    priority: 'medium',
  },
  {
    id: 'a4',
    title: 'Documentos: imprimir seguro de viaje',
    type: 'document',
    date: '2025-09-01',
    countries: ['España'],
    description: 'Imprimir o guardar en el teléfono el seguro de viaje.',
    status: 'pending',
    priority: 'high',
  },
  // Day 2 - Madrid → Escocia (vuelo)
  {
    id: 'a5',
    title: 'Vuelo MAD → EDI (Iberia IB3502)',
    type: 'flight',
    date: '2025-09-02',
    startTime: '07:45',
    endTime: '11:30',
    countries: ['España', 'Escocia'],
    originCountry: 'España',
    destinationCountry: 'Escocia',
    city: 'Madrid / Edimburgo',
    location: 'Aeropuerto Madrid-Barajas T4',
    description: 'Vuelo directo Madrid–Edimburgo. Facturar equipaje online.',
    status: 'confirmed',
    priority: 'high',
    link: 'https://example.com/flight-booking',
  },
  {
    id: 'a6',
    title: 'Traslado al centro de Edimburgo',
    type: 'transfer',
    date: '2025-09-02',
    startTime: '12:00',
    countries: ['Escocia'],
    city: 'Edimburgo',
    description: 'Airlink 100 bus desde el aeropuerto.',
    status: 'pending',
    priority: 'medium',
  },
  {
    id: 'a7',
    title: 'Check-in The Balmoral Hotel',
    type: 'accommodation',
    date: '2025-09-02',
    startTime: '15:00',
    countries: ['Escocia'],
    city: 'Edimburgo',
    location: '1 Princes Street, Edinburgh',
    description: 'Hotel 5 estrellas frente a Waverley Station.',
    status: 'confirmed',
    priority: 'high',
  },
  // Day 3 - Edimburgo
  {
    id: 'a8',
    title: 'Visita Castillo de Edimburgo',
    type: 'sightseeing',
    date: '2025-09-03',
    startTime: '09:30',
    endTime: '12:30',
    countries: ['Escocia'],
    city: 'Edimburgo',
    location: 'Castlehill, Edinburgh EH1 2NG',
    description: 'Comprar entradas online con antelación.',
    status: 'reserved',
    priority: 'high',
    link: 'https://www.edinburghcastle.scot/',
  },
  {
    id: 'a9',
    title: 'Cena con degustación de whisky',
    type: 'food',
    date: '2025-09-03',
    startTime: '20:00',
    endTime: '22:30',
    countries: ['Escocia'],
    city: 'Edimburgo',
    description: 'Restaurante escocés con maridaje de whisky local.',
    status: 'pending',
    priority: 'medium',
  },
  // Day 4 - París, Francia
  {
    id: 'a10',
    title: 'Vuelo EDI → CDG (easyJet EZY3312)',
    type: 'flight',
    date: '2025-09-04',
    startTime: '08:00',
    endTime: '10:45',
    countries: ['Escocia', 'Francia'],
    originCountry: 'Escocia',
    destinationCountry: 'Francia',
    city: 'Edimburgo / París',
    status: 'confirmed',
    priority: 'high',
  },
  {
    id: 'a11',
    title: 'Check-in Hôtel Le Marais',
    type: 'accommodation',
    date: '2025-09-04',
    startTime: '14:00',
    countries: ['Francia'],
    city: 'París',
    location: 'Rue de Rivoli 48, Paris',
    status: 'confirmed',
    priority: 'high',
  },
  {
    id: 'a12',
    title: 'Torre Eiffel al atardecer',
    type: 'sightseeing',
    date: '2025-09-04',
    startTime: '19:00',
    endTime: '21:00',
    countries: ['Francia'],
    city: 'París',
    location: 'Champ de Mars, Paris',
    description: 'Ver la Torre Eiffel iluminada al caer la noche.',
    status: 'pending',
    priority: 'medium',
  },
  // Day 5 - Roma, Italia
  {
    id: 'a13',
    title: 'Tren París → Roma (TGV + Frecciarossa)',
    type: 'train',
    date: '2025-09-06',
    startTime: '07:00',
    endTime: '15:30',
    countries: ['Francia', 'Italia'],
    originCountry: 'Francia',
    destinationCountry: 'Italia',
    city: 'París / Roma',
    location: 'Gare de Lyon, Paris',
    description: 'Cambio de tren en Milán. Boletos comprados.',
    status: 'confirmed',
    priority: 'high',
    link: 'https://example.com/train-booking',
  },
  {
    id: 'a14',
    title: 'Check-in Hotel Foro Romano',
    type: 'accommodation',
    date: '2025-09-06',
    startTime: '16:00',
    countries: ['Italia'],
    city: 'Roma',
    location: 'Via Sacra, Roma',
    status: 'confirmed',
    priority: 'high',
  },
  {
    id: 'a15',
    title: 'Visita al Coliseo',
    type: 'sightseeing',
    date: '2025-09-07',
    startTime: '09:00',
    endTime: '12:00',
    countries: ['Italia'],
    city: 'Roma',
    location: 'Piazza del Colosseo, Roma',
    description: 'Entrada con tour guiado. Reservar con anticipación.',
    status: 'reserved',
    priority: 'high',
  },
  {
    id: 'a16',
    title: 'Cena en Trastevere',
    type: 'food',
    date: '2025-09-07',
    startTime: '20:00',
    countries: ['Italia'],
    city: 'Roma',
    description: 'Barrio bohemio con excelente gastronomía romana.',
    status: 'pending',
    priority: 'low',
  },
  // Day transit: Italia → Suiza
  {
    id: 'a17',
    title: 'Tren Roma → Lucerna (EuroCity EC)',
    type: 'train',
    date: '2025-09-08',
    startTime: '08:15',
    endTime: '16:00',
    countries: ['Italia', 'Suiza'],
    originCountry: 'Italia',
    destinationCountry: 'Suiza',
    city: 'Roma / Lucerna',
    location: 'Termini, Roma',
    description: 'Tren panorámico a través de los Alpes. ¡Impresionante!',
    status: 'confirmed',
    priority: 'high',
  },
  {
    id: 'a18',
    title: 'Check-in Hotel Des Balances, Lucerna',
    type: 'accommodation',
    date: '2025-09-08',
    startTime: '17:00',
    countries: ['Suiza'],
    city: 'Lucerna',
    location: 'Unter der Egg 6, Luzern',
    status: 'confirmed',
    priority: 'high',
  },
  {
    id: 'a19',
    title: 'Paseo nocturno por el Puente de la Capilla',
    type: 'sightseeing',
    date: '2025-09-08',
    startTime: '20:00',
    countries: ['Suiza'],
    city: 'Lucerna',
    location: 'Kapellbrücke, Luzern',
    description: 'El puente de madera cubierto más antiguo de Europa.',
    status: 'pending',
    priority: 'medium',
  },
  // Suiza day
  {
    id: 'a20',
    title: 'Excursión Monte Pilatus',
    type: 'sightseeing',
    date: '2025-09-09',
    startTime: '09:00',
    endTime: '17:00',
    countries: ['Suiza'],
    city: 'Lucerna',
    description: 'Tomar el funicular más empinado del mundo. Comprar tickets.',
    status: 'pending',
    priority: 'high',
    link: 'https://www.pilatus.ch/',
  },
  {
    id: 'a21',
    title: 'Comprar chocolate y reloj suizo',
    type: 'shopping',
    date: '2025-09-09',
    countries: ['Suiza'],
    city: 'Lucerna',
    description: 'Souvenirs: chocolates Lindt, navaja suiza, reloj.',
    status: 'pending',
    priority: 'low',
  },
  // Reminder
  {
    id: 'a22',
    title: 'Verificar pasaporte y visas',
    type: 'reminder',
    date: '2025-09-01',
    countries: ['España'],
    description: 'Confirmar que el pasaporte no vence antes de 6 meses del viaje.',
    status: 'pending',
    priority: 'high',
  },
]

export const SAMPLE_TRAVEL_DAYS: TravelDay[] = [
  { date: '2025-09-01', countries: ['España'],             mainCity: 'Madrid' },
  { date: '2025-09-02', countries: ['España', 'Escocia'],  mainCity: 'Edimburgo' },
  { date: '2025-09-03', countries: ['Escocia'],            mainCity: 'Edimburgo' },
  { date: '2025-09-04', countries: ['Escocia', 'Francia'], mainCity: 'París' },
  { date: '2025-09-05', countries: ['Francia'],            mainCity: 'París' },
  { date: '2025-09-06', countries: ['Francia', 'Italia'],  mainCity: 'Roma' },
  { date: '2025-09-07', countries: ['Italia'],             mainCity: 'Roma' },
  { date: '2025-09-08', countries: ['Italia', 'Suiza'],    mainCity: 'Lucerna' },
  { date: '2025-09-09', countries: ['Suiza'],              mainCity: 'Lucerna' },
]
