import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTripFinance1784332900000 implements MigrationInterface {
  name = 'CreateTripFinance1784332900000';
  async up(q: QueryRunner): Promise<void> {
    await q.query(`ALTER TABLE "trips" ADD COLUMN IF NOT EXISTS "baseCurrency" varchar(3) NOT NULL DEFAULT 'USD'`);
    await q.query(`ALTER TABLE "activities" ADD COLUMN IF NOT EXISTS "priceMinor" bigint, ADD COLUMN IF NOT EXISTS "priceCurrency" varchar(3), ADD COLUMN IF NOT EXISTS "priceType" varchar, ADD COLUMN IF NOT EXISTS "financialStatus" varchar, ADD COLUMN IF NOT EXISTS "financialParticipantUserIds" uuid[] NOT NULL DEFAULT '{}', ADD COLUMN IF NOT EXISTS "financialPayerUserId" uuid, ADD COLUMN IF NOT EXISTS "paidAt" date, ADD COLUMN IF NOT EXISTS "paymentReferenceUrl" varchar`);
    await q.query(`CREATE TABLE IF NOT EXISTS "trip_budgets" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL UNIQUE REFERENCES "trips"("id") ON DELETE CASCADE, "amountMinor" bigint NOT NULL CHECK ("amountMinor" >= 0), "currency" varchar(3) NOT NULL, "categoryBudgets" jsonb NOT NULL DEFAULT '{}', "personalBudgets" jsonb NOT NULL DEFAULT '{}', "alertThresholds" integer[] NOT NULL DEFAULT '{75,90,100}', "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now())`);
    await q.query(`CREATE TABLE IF NOT EXISTS "expenses" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL REFERENCES "trips"("id") ON DELETE CASCADE, "title" varchar(180) NOT NULL, "originalAmountMinor" bigint NOT NULL CHECK ("originalAmountMinor" > 0), "originalCurrency" varchar(3) NOT NULL, "exchangeRate" numeric(24,12) NOT NULL DEFAULT 1 CHECK ("exchangeRate" > 0), "convertedAmountMinor" bigint NOT NULL CHECK ("convertedAmountMinor" > 0), "baseCurrency" varchar(3) NOT NULL, "exchangeRateDate" date, "exchangeRateSource" varchar, "category" varchar(40) NOT NULL, "subcategory" varchar, "incurredAt" timestamptz NOT NULL, "city" varchar, "createdByUserId" uuid NOT NULL, "updatedByUserId" uuid, "payerUserId" uuid NOT NULL, "expenseType" varchar NOT NULL, "splitMethod" varchar NOT NULL, "activityId" uuid UNIQUE REFERENCES "activities"("id") ON DELETE SET NULL, "paymentMethod" varchar, "status" varchar NOT NULL DEFAULT 'paid', "notes" text, "receiptUrl" varchar, "items" jsonb NOT NULL DEFAULT '[]', "recurringGroupId" uuid, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(), "deletedAt" timestamptz)`);
    await q.query(`CREATE TABLE IF NOT EXISTS "expense_splits" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "expenseId" uuid NOT NULL REFERENCES "expenses"("id") ON DELETE CASCADE, "participantUserId" uuid NOT NULL, "amountMinor" bigint NOT NULL CHECK ("amountMinor" >= 0), "percentage" numeric(9,6), "shares" numeric(16,6), "generatesDebt" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_expense_split_participant" UNIQUE ("expenseId","participantUserId"))`);
    await q.query(`CREATE TABLE IF NOT EXISTS "settlements" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL REFERENCES "trips"("id") ON DELETE CASCADE, "fromUserId" uuid NOT NULL, "toUserId" uuid NOT NULL, "amountMinor" bigint NOT NULL CHECK ("amountMinor" > 0), "currency" varchar(3) NOT NULL, "settledAt" timestamptz NOT NULL, "note" text, "referenceUrl" varchar, "status" varchar NOT NULL DEFAULT 'posted', "createdByUserId" uuid NOT NULL, "voidedByUserId" uuid, "voidedAt" timestamptz, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(), CHECK ("fromUserId" <> "toUserId"))`);
    await q.query(`CREATE TABLE IF NOT EXISTS "exchange_rates" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL REFERENCES "trips"("id") ON DELETE CASCADE, "fromCurrency" varchar(3) NOT NULL, "toCurrency" varchar(3) NOT NULL, "rate" numeric(24,12) NOT NULL CHECK ("rate" > 0), "rateDate" date NOT NULL, "source" varchar, "createdByUserId" uuid NOT NULL, "createdAt" timestamptz NOT NULL DEFAULT now())`);
    await q.query(`CREATE INDEX IF NOT EXISTS "IDX_expenses_trip_date" ON "expenses"("tripId","incurredAt"); CREATE INDEX IF NOT EXISTS "IDX_expenses_trip_category" ON "expenses"("tripId","category"); CREATE INDEX IF NOT EXISTS "IDX_expenses_trip_payer" ON "expenses"("tripId","payerUserId"); CREATE INDEX IF NOT EXISTS "IDX_expense_splits_participant" ON "expense_splits"("participantUserId"); CREATE INDEX IF NOT EXISTS "IDX_settlements_trip_date" ON "settlements"("tripId","settledAt"); CREATE INDEX IF NOT EXISTS "IDX_exchange_rates_trip_pair_date" ON "exchange_rates"("tripId","fromCurrency","toCurrency","rateDate")`);
  }
  async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP TABLE IF EXISTS "exchange_rates"; DROP TABLE IF EXISTS "settlements"; DROP TABLE IF EXISTS "expense_splits"; DROP TABLE IF EXISTS "expenses"; DROP TABLE IF EXISTS "trip_budgets"`);
    await q.query(`ALTER TABLE "activities" DROP COLUMN IF EXISTS "paymentReferenceUrl", DROP COLUMN IF EXISTS "paidAt", DROP COLUMN IF EXISTS "financialPayerUserId", DROP COLUMN IF EXISTS "financialParticipantUserIds", DROP COLUMN IF EXISTS "financialStatus", DROP COLUMN IF EXISTS "priceType", DROP COLUMN IF EXISTS "priceCurrency", DROP COLUMN IF EXISTS "priceMinor"`);
    await q.query(`ALTER TABLE "trips" DROP COLUMN IF EXISTS "baseCurrency"`);
  }
}
