import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTravelerProfile1784593000000 implements MigrationInterface {
  name='CreateTravelerProfile1784593000000';
  public async up(q:QueryRunner):Promise<void>{
    await q.query(`CREATE TYPE "travel_documents_type_enum" AS ENUM ('identity','passport','visa','immigration_permit','driver_license','international_driver_permit','vaccination','prescription','medical_certificate','travel_insurance','assistance_certificate','accommodation','other')`);
    await q.query(`CREATE TYPE "travel_documents_sensitivity_enum" AS ENUM ('standard','sensitive','highly_sensitive')`);
    await q.query(`CREATE TYPE "traveler_resources_kind_enum" AS ENUM ('insurance','emergency_contact','important_address','medication','reminder')`);
    await q.query(`CREATE TYPE "trip_document_checklist_status_enum" AS ENUM ('pending','in_progress','completed','not_applicable')`);
    await q.query(`CREATE TABLE "traveler_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "personal" jsonb NOT NULL DEFAULT '{}', "medical" jsonb NOT NULL DEFAULT '{}', "privacy" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_traveler_profiles" PRIMARY KEY ("id"))`);
    await q.query(`CREATE UNIQUE INDEX "UQ_traveler_profiles_user" ON "traveler_profiles" ("userId")`);
    await q.query(`CREATE TABLE "travel_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "travel_documents_type_enum" NOT NULL, "displayName" varchar(160) NOT NULL, "issuingCountry" varchar(2), "documentNumber" varchar(255), "issuedAt" date, "expiresAt" date, "holderName" varchar(160), "notes" text, "tags" text[] NOT NULL DEFAULT '{}', "fileIds" uuid[] NOT NULL DEFAULT '{}', "sensitivity" "travel_documents_sensitivity_enum" NOT NULL DEFAULT 'sensitive', "favorite" boolean NOT NULL DEFAULT false, "details" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "deletedAt" TIMESTAMPTZ, CONSTRAINT "PK_travel_documents" PRIMARY KEY ("id"))`);
    await q.query(`CREATE INDEX "IDX_travel_documents_owner_type" ON "travel_documents" ("userId","type")`); await q.query(`CREATE INDEX "IDX_travel_documents_owner_expiry" ON "travel_documents" ("userId","expiresAt")`);
    await q.query(`CREATE TABLE "traveler_resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "kind" "traveler_resources_kind_enum" NOT NULL, "name" varchar(160) NOT NULL, "data" jsonb NOT NULL DEFAULT '{}', "favorite" boolean NOT NULL DEFAULT false, "priority" integer NOT NULL DEFAULT 0, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "deletedAt" TIMESTAMPTZ, CONSTRAINT "PK_traveler_resources" PRIMARY KEY ("id"))`); await q.query(`CREATE INDEX "IDX_traveler_resources_owner_kind" ON "traveler_resources" ("userId","kind")`);
    await q.query(`CREATE TABLE "trip_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tripId" uuid NOT NULL, "documentId" uuid NOT NULL, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_trip_documents" PRIMARY KEY ("id"), CONSTRAINT "UQ_trip_documents_trip_document" UNIQUE ("tripId","documentId"), CONSTRAINT "FK_trip_documents_trip" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE CASCADE, CONSTRAINT "FK_trip_documents_document" FOREIGN KEY ("documentId") REFERENCES "travel_documents"("id") ON DELETE CASCADE)`); await q.query(`CREATE INDEX "IDX_trip_documents_owner_trip" ON "trip_documents" ("userId","tripId")`);
    await q.query(`CREATE TABLE "trip_document_checklist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tripId" uuid NOT NULL, "label" varchar(180) NOT NULL, "status" "trip_document_checklist_status_enum" NOT NULL DEFAULT 'pending', "suggested" boolean NOT NULL DEFAULT false, "position" integer NOT NULL DEFAULT 0, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT "PK_trip_document_checklist" PRIMARY KEY ("id"), CONSTRAINT "FK_trip_document_checklist_trip" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE CASCADE)`); await q.query(`CREATE INDEX "IDX_trip_document_checklist_owner_trip" ON "trip_document_checklist" ("userId","tripId")`);
  }
  public async down(q:QueryRunner):Promise<void>{ await q.query(`DROP TABLE "trip_document_checklist"`); await q.query(`DROP TABLE "trip_documents"`); await q.query(`DROP TABLE "traveler_resources"`); await q.query(`DROP TABLE "travel_documents"`); await q.query(`DROP TABLE "traveler_profiles"`); await q.query(`DROP TYPE "trip_document_checklist_status_enum"`); await q.query(`DROP TYPE "traveler_resources_kind_enum"`); await q.query(`DROP TYPE "travel_documents_sensitivity_enum"`); await q.query(`DROP TYPE "travel_documents_type_enum"`); }
}
